version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: clubcore_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pw
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
