services:
  clubcoreapi:
    image: ${DOCKER_REGISTRY-}clubcoreapi
    build:
      context: .
      dockerfile: ../src/Clubcore.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  postgres:
    image: postgres:latest
    container_name: clubcore_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pw
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - ./bin/postgres:/var/lib/postgresql/data
